name: haskell-weekly
version: 0.0.0

category: Web
description: Haskell Weekly is an email newsletter.
extra-source-files:
  - CODE_OF_CONDUCT.markdown
  - content/**/*
  - CONTRIBUTING.markdown
  - README.markdown
github: haskellweekly/haskellweekly.github.io
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
synopsis: An email newsletter.

executables:
  haskell-weekly:
    dependencies:
      base: '>= 4.10.1 && < 4.12'
      cmark: '>= 0.5.6 && < 0.6'
      directory: '>= 1.3.0 && < 1.4'
      filepath: '>= 1.4.1 && < 1.5'
      text: '>= 1.2.2 && < 1.3'
      time: '>= 1.8.0 && < 1.9'
    ghc-options:
      - -rtsopts
      - -threaded
      - -Weverything
      - -Wno-implicit-prelude
      - -Wno-safe
      - -Wno-unsafe
    main: haskell-weekly.hs
    source-dirs: executables
